// ABOUTME: Bridge between alexadhy/agent-pi and gentle-pi capabilities.
// Provides gentle_status and gentle_skills tools without modifying gentle-pi.
// Gentle-pi remains the source of truth for SDD preflight and skill registry.

import { join } from "node:path";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { resolveSkillsForTask, loadSkillContent } from "./lib/gentle-skill-loader.ts";
import {
	loadPreflight,
	isCaptured,
	type PreflightState,
} from "./lib/sdd-preflight.ts";

// ── gentle-pi resolution ──────────────────────────────────────────────────────

function resolveGentlePi(): { root: string; version: string } | null {
	// gentle-pi is installed at <agent-home>/npm/node_modules/gentle-pi/
	// It is NOT a standard npm package — scan known paths
	const candidates = [
		join(homedir(), ".pi", "agent", "npm", "node_modules", "gentle-pi"),
		join(homedir(), ".pi", "agent", "node_modules", "gentle-pi"),
	];
	for (const candidate of candidates) {
		const pkgPath = join(candidate, "package.json");
		if (existsSync(pkgPath)) {
			try {
				const { version } = JSON.parse(readFileSync(pkgPath, "utf-8"));
				return { root: candidate, version };
			} catch {
				// continue
			}
		}
	}
	return null;
}

// ── Extension ────────────────────────────────────────────────────────────────

export default function (pi: ExtensionAPI) {
	const gp = resolveGentlePi();

	// Mark gentle-pi availability globally so mode prompts can gate on it
	(globalThis as any).__gentlePiAvailable = gp !== null;
	(globalThis as any).__gentlePiRoot = gp?.root ?? null;
	(globalThis as any).__gentlePiVersion = gp?.version ?? null;

	// ── gentle_status tool ───────────────────────────────────────────────────

	pi.registerTool({
		name: "gentle_status",
		label: "Gentle PI Status",
		description:
			"Show which gentle-pi capabilities are available in this session: version, preflight state, skill registry, and asset counts.",
		parameters: Type.Object({}),
		async execute(_toolCallId, _params, _signal, _onUpdate, _ctx) {
			const status = {
				gentlePiAvailable: gp !== null,
				version: gp?.version ?? null,
				root: gp?.root ?? null,
				preflightAvailable: false,
				skillRegistryAvailable: false,
				assets: null as { agents: number; chains: number; support: number } | null,
				message: "",
			};

			if (!gp) {
				status.message =
					"gentle-pi not found in npm modules. Install with: pi install npm:gentle-pi";
				return {
					content: [{ type: "text", text: JSON.stringify(status, null, 2) }],
					details: status,
				};
			}

			// Check preflight availability via the local re-export (which delegates to gentle-pi)
			try {
				const preflight = loadPreflight(process.cwd());
				status.preflightAvailable = isCaptured(preflight) || preflight.captured;
			} catch {
				status.preflightAvailable = false;
			}

			// Check skill registry availability (generated by gentle-pi on session_start)
			const cwd = process.cwd();
			const registryPath = join(cwd, ".atl", "skill-registry.md");
			status.skillRegistryAvailable = existsSync(registryPath);

			// Count gentle-pi assets
			try {
				const assetsRoot = join(gp.root, "assets");
				if (existsSync(assetsRoot)) {
					const agents = existsSync(join(assetsRoot, "agents"))
						? readFileSync(join(assetsRoot, "agents"), "utf-8")
							.split("\n")
							.filter((f) => f.endsWith(".md") && !f.startsWith("_")).length
						: 0;
					const chains = existsSync(join(assetsRoot, "chains"))
						? readFileSync(join(assetsRoot, "chains"), "utf-8")
							.split("\n")
							.filter((f) => f.endsWith(".md") && !f.startsWith("_")).length
						: 0;
					const support = existsSync(join(assetsRoot, "support"))
						? readFileSync(join(assetsRoot, "support"), "utf-8")
							.split("\n")
							.filter((f) => f.endsWith(".md") && !f.startsWith("_")).length
						: 0;
					status.assets = { agents, chains, support };
				}
			} catch {
				status.assets = null;
			}

			status.message = `gentle-pi ${gp.version} available at ${gp.root}`;
			return {
				content: [{ type: "text", text: JSON.stringify(status, null, 2) }],
				details: status,
			};
		},
	});

	// ── gentle_skills tool ──────────────────────────────────────────────────

	pi.registerTool({
		name: "gentle_skills",
		label: "Gentle PI Skills",
		description:
			"Resolve project skills from gentle-pi's .atl/skill-registry.md for a given task and target files. Returns matched skill paths for injection into scout subagent prompts.",
		parameters: Type.Object({
			task: Type.String({
				description: "Task description to match against skill triggers",
			}),
			targetFiles: Type.Optional(
				Type.Array(Type.String(), {
					description: "File paths being worked on (used for extension/path matching)",
				}),
			),
		}),
		async execute(_toolCallId, params, _signal, _onUpdate, _ctx) {
			const { task, targetFiles = [] } = params as {
				task: string;
				targetFiles?: string[];
			};

			if (!gp) {
				return {
					content: [
						{
							type: "text",
							text: "gentle-pi not available — cannot resolve skills.",
						},
					],
					details: { gentlePiAvailable: false, skills: [], resolved: false },
				};
			}

			const cwd = process.cwd();
			const registryPath = join(cwd, ".atl", "skill-registry.md");
			const resolution = resolveSkillsForTask(task, targetFiles, registryPath);

			// Also load skill content for matched skills
			const matchedPaths = resolution.skills.map((s) => s.path);
			const content = loadSkillContent(matchedPaths);

			const result = {
				gentlePiAvailable: true,
				gentlePiVersion: gp.version,
				registryPath: resolution.registryPath,
				skill_resolution: resolution.skill_resolution,
				skills: resolution.skills.map((s) => ({
					name: s.name,
					trigger: s.trigger,
					scope: s.scope,
					path: s.path,
					content: content[s.path] ?? null,
				})),
			};

			return {
				content: [
					{
						type: "text",
						text: JSON.stringify(result, null, 2),
					},
				],
				details: result,
			};
		},
	});
}
